### ISSUE TITLE
Missing compressWitness

### ISSUE THREAD

**Issue by signorecello** [noir-lang/acvm-simulator-wasm#2]
### Aim

Trying to get witness in a Buffer instead of a Map so I can inject it to `bb.js`

### Expected Behavior

I was expecting this package to have the `compressWitness` just like in the `acvm` [package](https://github.com/noir-lang/acvm-simulator/blob/master/test/shared/witness_compression.ts)

### Bug

This method doesn't exist in this package

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
@TomAFrench would you be able to take a look?

**Comment by TomAFrench** [comment]
Sure thing, I've updated the build artifacts in this repository to match the acvm-simulator state as of https://github.com/noir-lang/acvm-simulator/commit/c79d0e93a73bf0f9de7a1991cd74abcee66b215d so this issue is resolved.

We can look at native support for compressed witnesses when I'm back from holiday.
